### ISSUE TITLE
카카오 소셜 로그인

### ISSUE THREAD

**Issue by n2ptune** [Tripandbnb/TripNbnb-project#4]
카카오 소셜 로그인 기능을 추가하기 전에 서로 의논이 필요할 것 같아 이슈 올립니다. 아래와 같은 시나리오를 생각해봤습니다.

- 페이지에서 [카카오 아이디로 로그인 하기] 버튼 혹은 이미지로 로그인
- 모바일 기기에서는 카카오톡 어플리케이션 실행 후 로그인 진행 PC에서는 카카오 홈페이지에서 직접 사용자가 이메일과 비밀번호를 입력해서 로그인을 진행
- 로그인을 완료하고 카카오로부터 받은 사용자 정보를 서버로 넘김 (아이디, 이메일 등)
- 해당 유저가 데이터베이스에 존재하지 않는 경우 프론트에서 받은 정보를 기반으로 데이터베이스에 저장 (일종의 회원가입 이라고 생각하시면 될 것 같습니다.)
- 프론트는 카카오로부터 발급받은 액세스 토큰, 리프레시 토큰을 가지고 있다가 API 요청이 필요할 때마다 토큰을 헤더에 넣어 서버에 전송
- 서버에서 토큰을 검증하고 알맞은 처리 후 응답

이렇게 설계하는 걸로 할까요? 혹시 이해가 안되시거나 따로 생각하신 점들이 있으시다면 댓글 달아주세요.

[https://developers.kakao.com/docs/latest/ko/kakaologin/common](https://developers.kakao.com/docs/latest/ko/kakaologin/common)

**Comment by HyungJunGoo** [comment]
제가 보기엔 좋은 시나리오 같습니다. 이 시나리오대로 진행하는걸로 해도 될거 같습니다. 👍 
구체적인 설계 진행에 대해서는 목요일에 짧게 언급하고 진행할까요?

**Comment by n2ptune** [comment]
네 알겠습니다. 구현이 어느정도 진행되면 이슈 닫겠습니다.

**Comment by yu-jin-song** [comment]
넵 알겠습니다!
